name: "CI"

on:
  pull_request:

permissions:
  contents: write
  actions: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout the repo
      - run: npm ci # install packages
      - run: npm test # run tests (configured to use jest-junit reporter)

        name: Ensure reports directory exists
      - run: mkdir -p .

      - uses: actions/upload-artifact@v4 # upload test results
        if: success() || failure()
        with:
          name: test-results
          path: jest-junit.xml
