name: "Process Test Results"

on:
  workflow_run:
    workflows: ["Test Report"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v2
        with:
          name: test-results # Nome do artefato gerado no primeiro workflow

      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: JEST Tests # Nome da seção que será exibida
          path: "*.xml" # Certifique-se de apontar corretamente para os arquivos gerados (ajuste se necessário)
          reporter: jest-junit # Formato do relatório gerado pelos testes
          fail-on-error: false
